apiVersion: 1

datasources:
  - name: CyberOracle-Postgres
    uid: cyberoracle
    type: postgres
    access: proxy
    url: db:5432
    database: cyberoracle
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
